runtime: custom
env: flex

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /(.*)
  static_files: build/\1
  upload: build/(.*)

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300