version: '3.7'
services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mydocker_client
    ports:
    - 8080:80
    volumes:
    - ./:/opt/Myapps/GraphQL-App
    - /opt/Myapps/GraphQL-App/node_modules
    environment:
      NODE_ENV: development      
      CHOKIDAR_USEPOLLING: 1