version: '2'
services:    
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    user: root  
    container_name: Myjenkins
    ports:
    - 8000:8080
    - 50000:50000
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock